### ISSUE TITLE
Implement hero sections

### ISSUE THREAD

**Issue by castrolem** [castrolem/elemental#4]
# Description

Easily set up with little mark up a center aligned content on both axis to show case a call-to-action or different images in the background.
## Tasks
- [ ] Design the markup for hero sections to accommodate most user cases.
- [ ] Add a Page header component when sections are not needed to be a determined height.
- [ ] Add documentation on how to implement both cases.
