### ISSUE TITLE
Add showcase for Grid system with images

### ISSUE THREAD

**Issue by castrolem** [castrolem/elemental#5]
# Description

Currently showcasing the grid system on all it's glorious without any content, which is kinda sad. We will need to add some awesome use cases for this to showcase the full potential.
## Tasks
- [ ] Add media images grid system showcase.
- [ ] Add showcase of shopping like experience.
- [ ] Add showcase of cards + grid view.
